### ISSUE TITLE
Prevent Looping to First Slide from Last

### ISSUE THREAD

**Issue by Thomsos** [phil-r/react-native-looped-carousel#101]
Is it currently possible to prevent looping to the beginning (when on the last slide) or looping to the end (when on the first)?

**Comment by viktorsec** [comment]
Unfortunately this is not currently supported. PRs are always welcome!

**Comment by Msspl-PrashenjeetRoy** [comment]
Is there any solution to prevent looping from last screen to first? There is same problem.

**Comment by wouterkool91** [comment]
I made a simple fix to disable looping, see [this commit](https://github.com/wouterkool91/react-native-looped-carousel/commit/63abde6058ddc91334ef99c08928e8bf35d1ccad). I only did some basic testing on iOS. Hope this can help you anyway.

**Comment by wouterkool** [comment]
I made a simple fix to disable looping, see [this commit](https://github.com/wouterkool/react-native-looped-carousel/commit/63abde6058ddc91334ef99c08928e8bf35d1ccad). I only did some basic testing on iOS. Hope this can help you anyway.

**Comment by Shpadoinkle** [comment]
isLooped set to false doesnt seem to work for android. too bad  :(

**Comment by akshaygore06** [comment]
It's working for ios and android correctly. Can you please create a PR?

**Comment by felipesousa** [comment]
@wouterkool you can create a PR with this things?

**Comment by wouterkool** [comment]
@akshaygore06 @felipesousa I created a pull request [#129](https://github.com/phil-r/react-native-looped-carousel/pull/129)

**Comment by phil-r** [comment]
`isLooped` property was added
