### ISSUE TITLE
arrowsStyle not getting applied

### ISSUE THREAD

**Issue by arcifius** [phil-r/react-native-looped-carousel#125]
I wanted to put a circle around the arrow icon but arrowsStyle isn't begin applied at all...

**Comment by felipesousa** [comment]
@arcifius hello bro'.

I create a PR resolving this issue! 

[https://github.com/phil-r/react-native-looped-carousel/pull/128](feature: add props to style left and right arrows.)

**Comment by arcifius** [comment]
Nice, hope it get accepted to master branch too :D

**Comment by felipesousa** [comment]
Hey @arcifius, I made [this module](https://www.npmjs.com/package/react-native-looped-carousel-improved), is just the improvement of these component with another things. <3

**Comment by phil-r** [comment]
@felipesousa Cool ^_^

I'll look into all arrows related PRs later)

**Comment by phil-r** [comment]
merged and live
