### ISSUE TITLE
Cannot read property 'measure' of null

### ISSUE THREAD

**Issue by bnerDY** [phil-r/react-native-looped-carousel#130]
really not sure about this
FYI  

"react": "16.0.0-alpha.6",
"react-native": "^0.44.0",
![image](https://user-images.githubusercontent.com/5085327/30075685-1f4503c8-92a9-11e7-87ea-1c72a8459c1b.png)

**Comment by masiamj** [comment]
+1

**Comment by assuncaojr** [comment]
+1

**Comment by i8wu** [comment]
https://github.com/phil-r/react-native-looped-carousel/pull/109

**Comment by phil-r** [comment]
#109 was merged
