### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by lironess** [phil-r/react-native-looped-carousel#132]
Can you please publish a new version?
I need that prop-types fix at package.json because the library shows an error for using the old propTypes from React.

Thanks!

**Comment by icfr** [comment]
you can use this in your package.json

> phil-r/react-native-looped-carousel#e23e1ad41e67ee9e95558e7df00c364fbb1b688b

**Comment by coman3** [comment]
for anyone, @icfr means to just run `npm install phil-r/react-native-looped-carousel#e23e1ad41e67ee9e95558e7df00c364fbb1b688b` instead. This fixed the issue right away.

**Comment by phil-r** [comment]
new version `0.1.8` was released, sorry for the delay 😢
