### ISSUE TITLE
Undefined PropTypes.node

### ISSUE THREAD

**Issue by ImAtome** [phil-r/react-native-looped-carousel#135]
Everything worked well until I update my packages.

This is where the problem come from : [https://imgur.com/a/tHmNx](url)
 Is someone else is facing this issue?

[UPDATE] : This is is due to React.PropTypes which is now removed from React and available on 'prop-types' npm package.

**Comment by icfr** [comment]
you can use this in your package.json

> phil-r/react-native-looped-carousel#e23e1ad41e67ee9e95558e7df00c364fbb1b688b

**Comment by bkniya** [comment]
Can you describe, how to use this code in my packege.json ?

**Comment by icfr** [comment]
look add [this](http://remarkablemark.org/blog/2016/09/19/npm-install-from-github/)

**Comment by bkniya** [comment]
Thank you for your reply, I have already installed this plugin but after update react-native has encountered this error

**Comment by mgiachetti** [comment]
@phil-r can you release a new version with this fix?
the latest version 0.1.7 does not have this.

**Comment by emarar** [comment]
+1

**Comment by emarar** [comment]
phil-r/react-native-looped-carousel#e23e1ad41e67ee9e95558e7df00c364fbb1b688b

works fine by the way. :)

**Comment by qalqi** [comment]
npm install phil-r/react-native-looped-carousel#e23e1ad41e67ee9e95558e7df00c364fbb1b688b

**Comment by phil-r** [comment]
Should be fixed in `0.1.8`
