### ISSUE TITLE
Undefined error in PropTypes.node

### ISSUE THREAD

**Issue by cerberusv2px** [phil-r/react-native-looped-carousel#142]
Facing error on line 21 in the library.
_react3.default.PropTypes.node in undefined.

version
react: 16.0.0
react-native: 0.50.3,

**Comment by TimbreApp** [comment]
I have this exact same error, might have to use a previous version of react native.

**Comment by HossamSamir** [comment]
I have the same issue, I looked it a bit and I found that the problem with ``View.propTypes`` is deprecated and instead ``ViewPropTypes`` is used from RN44.
will you guys upgrade soon?

**Comment by HossamSamir** [comment]
[react-native-swiper](https://github.com/leecade/) works well for me though if you're looking for an alternative .

**Comment by phil-r** [comment]
Should be fixed as of `0.1.8`

**Comment by cerberusv2px** [comment]
@phil-r Too late broda

**Comment by phil-r** [comment]
`¯\_(ツ)_/¯`
