### ISSUE TITLE
Did it support scroll to specified position

### ISSUE THREAD

**Issue by ChaseChan** [phil-r/react-native-looped-carousel#145]
I use react-native-swiper and want it to scroll to specified,it supply an api which calls scrollBy,but it seems not good,when i changed it first time,it work correctly,but the second time I tried again,it give me a wrong position.So Your document do not introduce you have scrollBy similar to react-native-swiper,do you have it or you will support it in the future?

**Comment by phil-r** [comment]
I've never used `react-native-swiper` but it's possible to animate to the given page using `animateToPage` method
