### ISSUE TITLE
Updating other props resets current page to 0 even when children are the same.

### ISSUE THREAD

**Issue by awochna** [phil-r/react-native-looped-carousel#146]
My carousel was set up to use arrows with custom text and also with a callback onAnimateNextPage. The purpose of that was to not render the left arrow (an empty Text element) when we were on the first page, but then enable the the left arrow on other pages.

Until a recent update to fix PropTypes, this worked out fine. With the latest update, trying to navigate to the next page resulted in no change to the Carousel's state's currentPage, displaying the second page, and selecting the first bullet. Successive attempts to navigate to the next page went through the animation, but resulted in the exact same thing. Trying to navigate backwards suddenly navigates to the last page.

There are not changes to the Carousel's children in the meantime, but the logic in componentWillRecieveProps is getting executed anyway. This means that it's executing too often and resetting the current page to 0 when it doesn't need to be.

I'll be submitting a PR shortly with a fix.

**Comment by phil-r** [comment]
I think it was fixed by #113, but I still want to look into your PR ^_^
