### ISSUE TITLE
not working on react native version 0.51.0

### ISSUE THREAD

**Issue by roysG** [phil-r/react-native-looped-carousel#150]
react-native-cli: 1.0.0
react-native: 0.51.0

I get error:
<img width="411" alt="screen shot 2018-01-30 at 20 32 21" src="https://user-images.githubusercontent.com/7311802/35584125-b6767918-05fc-11e8-9c3f-1dd266b52898.png">

**Comment by ricardosasilva** [comment]
Check #135.

**Comment by phil-r** [comment]
Should be fixed in `0.1.8`
