### ISSUE TITLE
Not an Issue. But Doubt

### ISSUE THREAD

**Issue by deva11** [phil-r/react-native-looped-carousel#151]
Can I generate dynamically this Slideshow ?? Is it possible to set custom time for each transition ??

How can I move to another View within Carousal tag Dynamically?

Is it possible to set the View programatically using prop "currentPage" from the list of generated Views?

**Comment by phil-r** [comment]
> Is it possible to set custom time for each transition ??

No

> How can I move to another View within Carousal tag Dynamically? Is it possible to set the View programatically using prop "currentPage" from the list of generated Views?

Yes, using `animateToPage`
