### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by angineering** [phil-r/react-native-looped-carousel#153]
Judging by the time of the last commit, the 213 forks and that it doesn't compile on react-native 0.49.5 >= it looks like this project is no longer being updated. Is this correct?

**Comment by rodmoreno** [comment]
hey @phil-r have you abandoned the project?

**Comment by phil-r** [comment]
Hi @angineering and @rodmoreno 

Yeah it was for some time, the number of issues and PRs was a bit too overwhelming for me to take care of. But I have some free time now to clean everything up ^_^
