### ISSUE TITLE
Styling of bullets

### ISSUE THREAD

**Issue by simonstewart** [phil-r/react-native-looped-carousel#41]
Great control!

Is it possible to style the bullets (eg: color)?

**Comment by phil-r** [comment]
@simonstewart Of course it's possible, we can add new property, like `bulletsStyle`
I'll try to add this during the week, or you can open a PR, this should be quite straightforward enhancement.

**Comment by crHand** [comment]
Hi! @simonstewart @phil-r 

FYI, I just made a PR that contemplates this request.

**Comment by gogumai** [comment]
Hi! @simonstewart @phil-r

FYI, I just made a PR that contemplates this request.

**Comment by nancyhuynh** [comment]
@gogumai  thanks - this is exactly what I was looking for since I need black bullets on a white background :)

@phil-r would it be possible to merge the PR soon? Thanks!

**Comment by simonstewart** [comment]
@gogumai thanks!

**Comment by phil-r** [comment]
Hey guys! 
@gogumai I've left a small comment for your PR, as soon as it's resolved I'll be happy to merge!

P.S. I'm sorry for the delay !

**Comment by duzliang** [comment]
We can styling bullets container View style, can we styling it's parent View style?  so we can control the position of bullets container

**Comment by Devikaelangovan** [comment]
is there any way to change the bullets position?

**Comment by dooubsam** [comment]
@Devikaelangovan Overwrite styles.

```json
{
  bulletsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  chosenBullet: {
    margin: 10,
    width: 10,
    height: 10,
    borderRadius: 20,
    backgroundColor: 'white',
  },
  bullet: {
    margin: 10,
    width: 10,
    height: 10,
    borderRadius: 20,
    backgroundColor: 'transparent',
    borderColor: 'white',
    borderWidth: 1,
  }
}
```

**Comment by rishabh-saxena** [comment]
@Devikaelangovan I have raised a PR for positioning of bullets.https://github.com/phil-r/react-native-looped-carousel/pull/137 .Lets see when it gets merged.

**Comment by phil-r** [comment]
You can use `bulletsContainerStyle`, Thanks @rishabh-saxena for the PR =)
