### ISSUE TITLE
Autoplay only works after a manual scroll

### ISSUE THREAD

**Issue by b8ne** [phil-r/react-native-looped-carousel#48]
On page load autoplay does not begin, however if i manually scroll 1 slide, it does autoplay after the expected delay.

**Comment by stuartjeasyodds** [comment]
Thanks @b8ne . Re initialising the timer works for me.

**Comment by b8ne** [comment]
Hey @stuartjeasyodds yeah i found that. Hence the referenced PR to automate it :)

**Comment by DeDuckProject** [comment]
This seems similar to the issue I've encountered #50 . only after a manual scroll the next steps are enabled. How do u init the timer? I want to check if it fixes my problem as well

**Comment by b8ne** [comment]
Ive submitted a PR to fix.

**Comment by DeDuckProject** [comment]
@b8ne tnx I see it

**Comment by b8ne** [comment]
All good mate. Didnt mean to be blunt. Just replying from phone.

**Comment by DeDuckProject** [comment]
@b8ne no worries mate ;) I implemented you PR and it didn't fix my issue.. so they are not from the same cause :(

**Comment by viktorsec** [comment]
@DeDuckProject I know it's a long time, but is this issue still existent?
