### ISSUE TITLE
setCurrent page method and isLooped prop

### ISSUE THREAD

**Issue by Yuriy1988** [phil-r/react-native-looped-carousel#58]
Your component is very nice! Thank You!
Could you provide this with method setPage: actually I do it with 
this.сarousel._setCurrentPage(cardNum);
this.сarousel._placeCritical(cardNum);

Also it would be nice to have isLooped prop :)

**Comment by kevindavis** [comment]
@Yuriy1988 can you share how you did that? my attempt failed :(

**Comment by Yuriy1988** [comment]
Here I have my carousel 

<Carousel
    ref={ref => (this.сarousel = ref)}
 >

and when I need - I just call this.сarousel._animateToPage(pageNum');

Actually I changed a little the source of сarousel, and if method above will not work for you - let me now, i can share working example;

**Comment by kevindavis** [comment]
@Yuriy1988 thanks for the reply! that helped me figure out how to have a reference to the carousel throughout the component

I put this.carousel._placeCritical(); in componentWillUpdate and it seems to have solved my problem

I'd be curious to see your changes though - do you have a diff?

**Comment by Yuriy1988** [comment]
@kevindavis 
Sorry, for late response, but i had a lot of work
here is diff
https://gist.github.com/Yuriy1988/b52c060540443c21e7fbbe4f92626a91
Actually, i don't remember what for i changed it :)

**Comment by kevindavis** [comment]
thanks!

**Comment by viktorsec** [comment]
It's not yet in the docs, but we renamed `_animateToPage()` to `animateToPage()`.

Feel free to call the method to slide the carousel programatically (it will do the animation as well).

We do also happily accept PRs for other functionality!

**Comment by wouterkool91** [comment]
As regards the isLooped prop, see my comment to #101.

**Comment by wouterkool** [comment]
As regards the isLooped prop, see my comment to #101.
